// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: notifierpb/notifier.proto

package notifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// template is the email template to render (see ghnotify/contract template names).
	Template string `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	// recipient is the single email address this call delivers to.
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// payload is the template-specific body as JSON (e.g. RepositoryUpdateEmailPayload).
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// idempotency_key deterministically identifies the notification so the server
	// sends each (key, recipient) email at most once across retries/redeliveries.
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_notifierpb_notifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifierpb_notifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_notifierpb_notifier_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *NotifyRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotifyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NotifyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type NotifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok is true when the email was delivered or was already delivered previously
	// (idempotent skip). The caller may advance last_seen_tag only when ok is true.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// reason carries a human-readable failure description when ok is false.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_notifierpb_notifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifierpb_notifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_notifierpb_notifier_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NotifyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_notifierpb_notifier_proto protoreflect.FileDescriptor

const file_notifierpb_notifier_proto_rawDesc = "" +
	"\n" +
	"\x19notifierpb/notifier.proto\x12\vnotifier.v1\"\x8c\x01\n" +
	"\rNotifyRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"8\n" +
	"\x0eNotifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2M\n" +
	"\bNotifier\x12A\n" +
	"\x06Notify\x12\x1a.notifier.v1.NotifyRequest\x1a\x1b.notifier.v1.NotifyResponseB\x1eZ\x1cghnotify/contract/notifierpbb\x06proto3"

var (
	file_notifierpb_notifier_proto_rawDescOnce sync.Once
	file_notifierpb_notifier_proto_rawDescData []byte
)

func file_notifierpb_notifier_proto_rawDescGZIP() []byte {
	file_notifierpb_notifier_proto_rawDescOnce.Do(func() {
		file_notifierpb_notifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifierpb_notifier_proto_rawDesc), len(file_notifierpb_notifier_proto_rawDesc)))
	})
	return file_notifierpb_notifier_proto_rawDescData
}

var file_notifierpb_notifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notifierpb_notifier_proto_goTypes = []any{
	(*NotifyRequest)(nil),  // 0: notifier.v1.NotifyRequest
	(*NotifyResponse)(nil), // 1: notifier.v1.NotifyResponse
}
var file_notifierpb_notifier_proto_depIdxs = []int32{
	0, // 0: notifier.v1.Notifier.Notify:input_type -> notifier.v1.NotifyRequest
	1, // 1: notifier.v1.Notifier.Notify:output_type -> notifier.v1.NotifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notifierpb_notifier_proto_init() }
func file_notifierpb_notifier_proto_init() {
	if File_notifierpb_notifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifierpb_notifier_proto_rawDesc), len(file_notifierpb_notifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifierpb_notifier_proto_goTypes,
		DependencyIndexes: file_notifierpb_notifier_proto_depIdxs,
		MessageInfos:      file_notifierpb_notifier_proto_msgTypes,
	}.Build()
	File_notifierpb_notifier_proto = out.File
	file_notifierpb_notifier_proto_goTypes = nil
	file_notifierpb_notifier_proto_depIdxs = nil
}
